{"name": "用户确认登陆 验证码错误", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_uesr_confirm_fail.Test_create_custodial_account object at 0x107d857f0>, test_title = '用户确认登陆 验证码错误'\nemail = '15873664023@163.com', oneTimePassword = '123456', status_code = 400, code = 2100000\n\n    @allure.story(\"User Connect Fail!\")\n    @allure.title('{test_title}')\n    @pytest.mark.parametrize('test_title,email,oneTimePassword,status_code,code', test_data)\n    def test_create_account_custodial(self, test_title, email,oneTimePassword, status_code, code):\n    \n        with allure.step(\"用户请求登陆\"):\n            connect_request = Http.HttpUtils.connect_req(email)\n>           assert connect_request.status_code == 200\nE           assert 400 == 200\nE            +  where 400 = <Response [400]>.status_code\n\nTestcase/Test_User/test_uesr_confirm_fail.py:32: AssertionError"}, "steps": [{"name": "用户请求登陆", "status": "failed", "statusDetails": {"message": "AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code\n", "trace": "  File \"/Users/lilong/Documents/Test_Api/Testcase/Test_User/test_uesr_confirm_fail.py\", line 32, in test_create_account_custodial\n    assert connect_request.status_code == 200\n"}, "start": 1673432941535, "stop": 1673432941798}], "attachments": [{"name": "log", "source": "5194d521-3089-4407-b56d-080280d305e6-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_title", "value": "'用户确认登陆 验证码错误'"}, {"name": "email", "value": "'15873664023@163.com'"}, {"name": "oneTimePassword", "value": "'123456'"}, {"name": "status_code", "value": "400"}, {"name": "code", "value": "2100000"}], "start": 1673432941535, "stop": 1673432941799, "uuid": "20415cba-4ccd-4e6b-8339-43e72ed29d5d", "historyId": "fd46224c220a02e0d214c82d0b44ec7e", "testCaseId": "8ceef3418acc8d9fb84fa541b73aaf3a", "fullName": "Testcase.Test_User.test_uesr_confirm_fail.Test_create_custodial_account#test_create_account_custodial", "labels": [{"name": "feature", "value": "Users Fail!"}, {"name": "story", "value": "User Connect Fail!"}, {"name": "parentSuite", "value": "Testcase.Test_User"}, {"name": "suite", "value": "test_uesr_confirm_fail"}, {"name": "subSuite", "value": "Test_create_custodial_account"}, {"name": "host", "value": "lilongdeMacBook-Pro.local"}, {"name": "thread", "value": "2630-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase.Test_User.test_uesr_confirm_fail"}]}